/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.coderbd.evedence;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class EvidenceFinalEx extends javax.swing.JFrame {

    /**
     * Creates new form EvidenceFinalEx
     */
    public EvidenceFinalEx() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Lbname = new javax.swing.JLabel();
        LbEmail = new javax.swing.JLabel();
        LbAge = new javax.swing.JLabel();
        LbGender = new javax.swing.JLabel();
        LbPassword = new javax.swing.JLabel();
        LbHobby = new javax.swing.JLabel();
        LbRound = new javax.swing.JLabel();
        LbNote = new javax.swing.JLabel();
        TxtName = new javax.swing.JTextField();
        TxtEmail = new javax.swing.JTextField();
        TxtAge = new javax.swing.JTextField();
        RdMale = new javax.swing.JRadioButton();
        RdFemale = new javax.swing.JRadioButton();
        CbReading = new javax.swing.JCheckBox();
        CbWriting = new javax.swing.JCheckBox();
        CbTraveling = new javax.swing.JCheckBox();
        ComBxSelectRound = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtAreaNote = new javax.swing.JTextArea();
        BtAdd = new javax.swing.JButton();
        BtReset = new javax.swing.JButton();
        BtClearTable = new javax.swing.JButton();
        BtExit = new javax.swing.JButton();
        BtReadFromFile = new javax.swing.JToggleButton();
        pwTxt = new javax.swing.JPasswordField();
        LbMsg = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel2.setBackground(new java.awt.Color(255, 255, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Student Regestration Form");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "My Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        Lbname.setText("Name :");

        LbEmail.setText("E - mail : ");

        LbAge.setText("Age :");

        LbGender.setText("Gendar :");

        LbPassword.setText("Password :");

        LbHobby.setText("Hobby :");

        LbRound.setText("Round :");

        LbNote.setText("Note :");

        TxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNameActionPerformed(evt);
            }
        });

        TxtAge.setText("0");
        TxtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtAgeKeyPressed(evt);
            }
        });

        buttonGroup1.add(RdMale);
        RdMale.setText("Male");

        buttonGroup1.add(RdFemale);
        RdFemale.setSelected(true);
        RdFemale.setText("Female");

        CbReading.setText("Reading");
        CbReading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbReadingActionPerformed(evt);
            }
        });

        CbWriting.setText("Writing");
        CbWriting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbWritingActionPerformed(evt);
            }
        });

        CbTraveling.setText("Traveling");

        ComBxSelectRound.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a round", "Round 35", "Round 36", "Round 37", "Round 38" }));
        ComBxSelectRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComBxSelectRoundActionPerformed(evt);
            }
        });

        TxtAreaNote.setColumns(20);
        TxtAreaNote.setRows(5);
        jScrollPane1.setViewportView(TxtAreaNote);

        BtAdd.setText("Add to Table & Wrte to File");
        BtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAddActionPerformed(evt);
            }
        });

        BtReset.setText("Reset");
        BtReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtResetActionPerformed(evt);
            }
        });

        BtClearTable.setText("Clear Table");
        BtClearTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtClearTableActionPerformed(evt);
            }
        });

        BtExit.setText("Exit");
        BtExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExitActionPerformed(evt);
            }
        });

        BtReadFromFile.setText("Read From File");
        BtReadFromFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtReadFromFileActionPerformed(evt);
            }
        });

        LbMsg.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BtAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(BtReset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtClearTable, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtExit))
                            .addComponent(BtReadFromFile, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LbNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LbRound, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LbHobby, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LbPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(LbGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LbAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LbEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lbname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtName)
                            .addComponent(TxtEmail)
                            .addComponent(TxtAge)
                            .addComponent(jScrollPane1)
                            .addComponent(pwTxt)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(RdMale)
                                        .addGap(26, 26, 26)
                                        .addComponent(RdFemale))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(CbReading)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CbWriting)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CbTraveling))
                                    .addComponent(ComBxSelectRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(LbMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(6, 6, 6))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Lbname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LbAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtAge, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RdMale)
                    .addComponent(RdFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbHobby, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbReading)
                    .addComponent(CbWriting)
                    .addComponent(CbTraveling))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbRound, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComBxSelectRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbNote, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LbMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtReset)
                            .addComponent(BtClearTable)
                            .addComponent(BtExit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtReadFromFile)))
                .addGap(9, 9, 9))
        );

        jPanel3.setBackground(new java.awt.Color(255, 189, 128));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Table", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        Table.setAutoCreateRowSorter(true);
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "E-mail", "Age", "Gender", "Password", "Hobby", "Round", "Note"
            }
        ));
        jScrollPane2.setViewportView(Table);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 281, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean checkEmailValidity(String email) {
        int atpos = email.indexOf("@");
        int dotpos = email.lastIndexOf(".");

        if (atpos > 1 && dotpos < email.length() - 3 && atpos < dotpos - 1 && email.length() >= 7) {
            return true;
        } else {
            return false;
        }
    }

    private void TxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNameActionPerformed

    private void CbWritingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbWritingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbWritingActionPerformed

    private void ComBxSelectRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComBxSelectRoundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComBxSelectRoundActionPerformed

    private void BtExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtExitActionPerformed

    private void BtResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtResetActionPerformed
        TxtName.setText("");
        TxtEmail.setText("");
        TxtAge.setText("0");
        RdFemale.setSelected(true);
        pwTxt.setText("");
        CbReading.setSelected(false);
        CbWriting.setSelected(false);
        CbTraveling.setSelected(false);
        ComBxSelectRound.setSelectedIndex(0);
        TxtAreaNote.setText("");
        LbMsg.setText("");
    }//GEN-LAST:event_BtResetActionPerformed

    private void BtClearTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtClearTableActionPerformed
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_BtClearTableActionPerformed

    private void BtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAddActionPerformed
        String name = "", email = "", age = "0", gender = "", password = "",
                hobby = "", round = "", note = "";
        if (TxtName.getText().length() < 1) {
            JOptionPane.showMessageDialog(null, "Enter your name...");
            
        } else if (!checkEmailValidity(TxtEmail.getText()) || TxtEmail.getText().length() < 1) {
            JOptionPane.showMessageDialog(null, "Enter your Valid Email...");
            
        } else if (Integer.parseInt(TxtAge.getText()) < 18 || Integer.parseInt(TxtAge.getText()) > 50) {
            JOptionPane.showMessageDialog(null, "Enter your age between 18-50...");
            
        }  else if (pwTxt.getText().length() < 5) {
            JOptionPane.showMessageDialog(null, "Enter Password at lest 5 digit...");
            
        } else if (buttonGroup1.getSelection().isSelected() == false) {
            JOptionPane.showMessageDialog(null, "Select a gender...");
            
        } else if (!CbReading.isSelected() && !CbWriting.isSelected() && !CbTraveling.isSelected()) {
            JOptionPane.showMessageDialog(null, "Select hobby...");
            
        }else if (ComBxSelectRound.getItemAt(ComBxSelectRound.getSelectedIndex()) == "Select a round") {
            JOptionPane.showMessageDialog(null, "Enter your Round...");
            
        } else if (TxtAreaNote.getText().length() < 5) {
            JOptionPane.showMessageDialog(null, "Enter note at lest 5 charecters...");
            
        } else {
            name = TxtName.getText();
            email = TxtEmail.getText();
            age = TxtAge.getText();

            if (RdMale.isSelected()) {
                gender = RdMale.getText();
            }

            if (RdFemale.isSelected()) {
                gender = RdFemale.getText();
            }

            if (CbReading.isSelected()) {
                hobby += CbReading.getText() + " ";
            }

            if (CbWriting.isSelected()) {
                hobby += CbWriting.getText() + " ";
            }

            if (CbTraveling.isSelected()) {
                hobby += CbTraveling.getText() + " ";
            }

            round = ComBxSelectRound.getItemAt(ComBxSelectRound.getSelectedIndex());
            note = TxtAreaNote.getText();

            Student stu = new Student(name, email, Integer.parseInt(age), gender, password, hobby, round, note);
            List<Student> list = new ArrayList<>();
            list.add(stu);

            DefaultTableModel model = (DefaultTableModel)Table.getModel();
            Object[] row = new Object[8];
            
            for(int i = 0; i< list.size(); i++){
            row[0] =list.get(i).getName();
            row[1] =list.get(i).getEmail();
            row[2] =list.get(i).getAge();
            row[3] =list.get(i).getGender();
            row[4] =list.get(i).getPassword();
            row[5] =list.get(i).getHobby();
            row[6] =list.get(i).getRound();
            row[7] =list.get(i).getNote();
            model.addRow(row);
            
                try {
                    Util.WriteToFile("sushmi", list);
                } catch (Exception e) {
                    Logger.getLogger(EvidenceFinalEx.class.getName()).log(Level.SEVERE,null,e);
                }
            
            }
            LbMsg.setText("Table added successfully & write to file...");
            
        }
    }//GEN-LAST:event_BtAddActionPerformed

    private void BtReadFromFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtReadFromFileActionPerformed
        String columns[] = {"Name",  "E-mail","Age", "Gender", "Password", "Hobby", "Round", "Note"};
        DefaultTableModel tableModel;
        tableModel = new DefaultTableModel(0, 8);
        tableModel.setColumnIdentifiers(columns);
        Table.setModel(tableModel);
        Util.displayStudentDataFromFile("sushmi", tableModel);
    }//GEN-LAST:event_BtReadFromFileActionPerformed

    private void TxtAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtAgeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAgeKeyPressed

    private void CbReadingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbReadingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbReadingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EvidenceFinalEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EvidenceFinalEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EvidenceFinalEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EvidenceFinalEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EvidenceFinalEx().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAdd;
    private javax.swing.JButton BtClearTable;
    private javax.swing.JButton BtExit;
    private javax.swing.JToggleButton BtReadFromFile;
    private javax.swing.JButton BtReset;
    private javax.swing.JCheckBox CbReading;
    private javax.swing.JCheckBox CbTraveling;
    private javax.swing.JCheckBox CbWriting;
    private javax.swing.JComboBox<String> ComBxSelectRound;
    private javax.swing.JLabel LbAge;
    private javax.swing.JLabel LbEmail;
    private javax.swing.JLabel LbGender;
    private javax.swing.JLabel LbHobby;
    private javax.swing.JLabel LbMsg;
    private javax.swing.JLabel LbNote;
    private javax.swing.JLabel LbPassword;
    private javax.swing.JLabel LbRound;
    private javax.swing.JLabel Lbname;
    private javax.swing.JRadioButton RdFemale;
    private javax.swing.JRadioButton RdMale;
    private javax.swing.JTable Table;
    private javax.swing.JTextField TxtAge;
    private javax.swing.JTextArea TxtAreaNote;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtName;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPasswordField pwTxt;
    // End of variables declaration//GEN-END:variables
}
